### ISSUE TITLE
LICENSE & Superscript

### ISSUE THREAD

**Issue by nitinkhosla79** [rainywalker/footNotes#1]
Hello! 
   What license is this plugin under? MIT?

Can footnote item show up as superscript(like it shows up in word)? We tried this plugin and the footnotes numbers showed up next to word. (example: footnote1).
Does tinymce has any footnotes functionality in open source or paid version?

**Comment by rainywalker** [comment]
Thank you for your interest.
The license is the GPL.

The footnote number should appear next to the word as you used.
Then style the footnote number with css in the View screen.

It doesn't make sense in the editor screen. When you click or hover over the footnote number.
Showing the content is key.

**Comment by rainywalker** [comment]
> Hello!
> What license is this plugin under? MIT?
> 
> Can footnote item show up as superscript(like it shows up in word)? We tried this plugin and the footnotes numbers showed up next to word. (example: footnote1).
> Does tinymce has any footnotes functionality in open source or paid version?

**Comment by rainywalker** [comment]
> Hello!
> What license is this plugin under? MIT?
> 
> Can footnote item show up as superscript(like it shows up in word)? We tried this plugin and the footnotes numbers showed up next to word. (example: footnote1).
> Does tinymce has any footnotes functionality in open source or paid version?

Thank you for your interest.
The license is the GPL.

The footnote number should appear next to the word as you used.
Then style the footnote number with css in the View screen.

It doesn't make sense in the editor screen. When you click or hover over the footnote number.
Showing the content is key.

**Comment by rainywalker** [comment]
Sorry.
You touched it incorrectly and it's closed.
